In [1]:
# Following along this notebook https://www.kaggle.com/neelkudu28/covid-19-visualizations-predictions-forecasting

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import datetime as dt
from datetime import timedelta

In [3]:
df = pd.read_csv('Covid 19/covid_19_data.csv', parse_dates=['Last Update'])
df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,2020-01-22 17:00:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,2020-01-22 17:00:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,2020-01-22 17:00:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,2020-01-22 17:00:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,2020-01-22 17:00:00,0.0,0.0,0.0

In [4]:
df.tail()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
68553,68554,07/20/2020,Zaporizhia Oblast,Ukraine,2020-07-21 04:38:46,678.0,20.0,551.0
68554,68555,07/20/2020,Zeeland,Netherlands,2020-07-21 04:38:46,791.0,69.0,0.0
68555,68556,07/20/2020,Zhejiang,Mainland China,2020-07-21 04:38:46,1270.0,1.0,1267.0
68556,68557,07/20/2020,Zhytomyr Oblast,Ukraine,2020-07-21 04:38:46,1602.0,34.0,1251.0
68557,68558,07/20/2020,Zuid-Holland,Netherlands,2020-07-21 04:38:46,11886.0,1305.0,0.0